function showData = importAsTable(filename, dataLines)
%importAsTable Import data from a text file
%  SHOWDATA = importAsTable(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  SHOWDATA = IMPORTFILE1(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  showData = importfile1("C:\repositories\demconChallenge\input.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-Aug-2024 09:18:35

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["showName", "startHour", "endHour"];
opts.VariableTypes = ["string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "showName", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "showName", "EmptyFieldRule", "auto");

% Import the data
showData = readtable(filename, opts);

end